DROP TABLE IF EXISTS TBL_JOBS;
  
CREATE TABLE TBL_JOBS (
  JOB_ID VARCHAR(250) PRIMARY KEY,
  JOB_URL VARCHAR(250),
  JOB_CREATED_AT VARCHAR(250),
  JOB_COMPANY VARCHAR(250),
  JOB_COMPANY_URL VARCHAR(250),
  JOB_TITLE VARCHAR(250),
  JOB_LOCATION VARCHAR(250),
  JOB_HOW_TO_APPLY VARCHAR(250),
  JOB_DESCRIPTION VARCHAR(250) DEFAULT NULL
);